version: "3.7"

volumes:
  postgres_data:
  redis_data:
  home:

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_IP}/24

services:
  postgres:
    image: postgres:11-alpine
    shm_size: 256M
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./docker/config/create-database.sh:/docker-entrypoint-initdb.d/create-database.sh"
    ports:
      - "${NETWORK_IP}:5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

  redis:
    image: redis:5.0-alpine
    volumes:
      - "redis_data:/data"
    ports:
      - "${NETWORK_IP}:6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${NETWORK_IP}:8025:8025"

  composer:
    image: iras/php7-composer:3
    user: "${PUID}"
    working_dir: "/community"
    entrypoint: /usr/bin/composer
    command: help
    volumes:
      - "./:/community"
      - "./storage/cache/composer:/composer/cache"
      - "./docker/config/bashrc.sh:/etc/profile.d/bashrc.sh"

  npm:
    image: iras/node:12
    user: "${PUID}"
    working_dir: "/community"
    entrypoint: /usr/bin/npm
    command: help
    volumes:
      - "./:/community"
      - "/storage/cache/npm:/home/node/.npm"
      - "./docker/config/bashrc.sh:/etc/profile.d/bashrc.sh"

  php:
    build:
      context: "."
      dockerfile: "docker/php-dev/Dockerfile"
    depends_on:
      - postgres
      - mailhog
      - redis
    working_dir: "/community"
    command: "run" # xdebug disabled
    volumes:
      - ".:/community"
      - "./storage/logs:/var/log/php"
      - "home:/home/www-user"
      - "./docker/config/xdebug.ini:/etc/php7/conf.d/xdebug.ini"
      - "./docker/config/bashrc.sh:/etc/profile.d/bashrc.sh"
    environment:
      - "UID=${PUID}"
      - "GID=${PGID}"
      - "APP_ENV=development"

  nginx:
    build:
      context: "."
      dockerfile: "docker/nginx/Dockerfile"
    depends_on:
      - php
    volumes:
      - "./public:/community/public"
      - "./storage/logs:/var/log/httpd"
      - "./docker/nginx/server.conf:/etc/nginx/conf.d/server/community.conf"
    ports:
      - "${NETWORK_IP}:80:8080"
    environment:
      - "UID=${PUID}"
      - "GID=${PGID}"
