version: "2.2"

volumes:
  postgres_data:
  npm_cache:
  composer_cache:

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"

  composer:
    image: iras/php7-composer:1
    user: "$UID"
    working_dir: "/community"
    entrypoint: /usr/bin/composer
    command: help
    volumes:
      - "./:/community"
      - "composer_cache:/composer/cache"

  npm:
    image: node:8-alpine
    user: "$UID"
    working_dir: "/community"
    entrypoint: /usr/local/bin/npm
    command: help
    volumes:
      - "./:/community"
      - "npm_cache:/home/node/.npm"
      - "./docker/node/path.sh:/etc/profile.d/path.sh"

  php:
    build:
      context: "."
      dockerfile: "docker/php/Dockerfile"
    user: "$UID"
    depends_on:
      - postgres
    working_dir: "/community"
    volumes:
      - ".:/community"
      - "./storage/logs:/var/log/php"
      - "./docker/php/xdebug.ini:/etc/php7/conf.d/xdebug.ini"
      - "./docker/php/debug.sh:/usr/bin/debug"
    environment:
      - "APP_ENV=development"

  nginx:
    build:
      context: "."
      dockerfile: "docker/nginx/Dockerfile"
    depends_on:
      - "php"
    volumes:
      - "./public:/community/public"
      - "./storage/logs:/var/log/httpd"
      - "./docker/nginx/server.conf:/etc/nginx/conf.d/server/community.conf"
    ports:
      - "8080:8080"
    environment:
      - "UID=$UID"
      - "GID=$GID"
